name: Build and Push Docker Image

on:
  push:
    branches:
      - main   # Tự động chạy khi bạn push lên nhánh main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Checkout mã nguồn
      - name: Checkout source code
        uses: actions/checkout@v4

      # Bước 2: Đăng nhập vào Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.phungtien }}
          password: ${{ secrets.tien123 }}

      # Bước 3: Build image Docker
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.phungtien }}/myapp:latest .

      # Bước 4: Push image lên Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.phungtien }}/myapp:latest
